### ISSUE TITLE
I am interested in implementing the PyTorch version of this project.

### ISSUE THREAD

**Issue by kajyuuen** [allanj/ner_incomplete_annotation#1]
I implemented your "Hard method" using PyTorch. 
But, I couldn't get the performance written in your paper.

Therefore, I would like to ask you about the project of the PyTorch implementation.
And, if you have time, I'd really appreciate it if you could give me your opinion on my implementation.

**Comment by allanj** [comment]
Thanks. I will try to finish it over the weekend. Please also point me to the link of your implementation, I will also take a look once I finished it.

**Comment by kajyuuen** [comment]
I really appreciate it.
My implementation is as follows:
https://github.com/kajyuuen/Fuzzy-LSTM-CRF

I'm looking forward to you finishing your implementation.

**Comment by allanj** [comment]
I'm fixing some of the bugs. will need some more days. Sorry for the delay

**Comment by allanj** [comment]
@kajyuuen I have implemented a hard approach but I didn't integrate the soft approach yet. You can check it out and let me know if you have any questions. Feel free to open the issue again.

By using PyTorch, I change the batch size to 10 and use SGD as the optimizer. Thus, the number of epochs is set to 50 for convergence. But I didn't go through the hyperparameters because my preliminary experimental results show it should be able to achieve the results in the paper without further tuning.

I will also look into your github repo.

**Comment by allanj** [comment]
Your code (hard_bilstm_crf) looks good to me. I might need to run your code to check though.
